### PR TITLE
fix: meta formatting

### LINKED ISSUE #1: fix: meta formatting
Hi @thedatabaseme 👋 

Thanks for setting this up! Excited to not reinvent the wheel re: spinning up kind clusters.

Getting a meta warning that blocks a repo install for your role:
```bash
[WARNING]: - kind was NOT installed successfully: this role does not appear to have a valid
meta/main.yml file.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Have a fix for it in a PR. Gimme a few minutes and I'll open it here.

### PR DESCRIPTION
**Pull request by pythoninthegrass**
Hello again!

Compared/contrasted with other roles I've used and saw that the indentation was off. Probably would've worked with meta being a child directory, but can't be bothered with lots of tinkering at the moment; highly unlikely moving a metadata directory will break any of the business logic.

Of course you're free to use whatever you'd like 👌 

## Main changes

- moved to top-level directory
- add .ansible-lint config
- fixed indentation levels (where the error was coming from)
- updated .gitignore to specify .vscode directory, include placeholder .gitkeep files, and add macos exclusions

Closes #1

### CODE REVIEW

**Comment by pythoninthegrass** [comment]
Removed a bunch of boilerplate comments as well. Hope you don't mind.

**Comment by thedatabaseme** [comment]
Hi @pythoninthegrass,
thanks for contributing.
you missed adapting the default playbook `ansible-kind.yml` for the new role path. Could you update this as well?

Philip

**Comment by thedatabaseme** [comment]
@pythoninthegrass 

alternatively. I really would like to keep the role under the role directory.

**Comment by pythoninthegrass** [comment]
Saw that. Moved it back to a draft.

In the process of debugging in a monolithic playbook.

Some upstream changes have occurred (e.g., the k8s kubectl repo moved) and some of the hard-coded package lists clobber a newer ubuntu distro.

I'll keep you posted, but it might be later this weekend until I can circle back.
________________________________

**Comment by pythoninthegrass** [comment]
> @pythoninthegrass
> 
> alternatively. I really would like to keep the role under the role directory.

Done! Just tested installing my version successfully via
```bash
λ ansible-galaxy install -r requirements.yml -f
Starting galaxy role install process
- kind (master) was installed successfully
```

My requirements.yml:
```yaml
roles:
  - name: kind
    src: https://github.com/pythoninthegrass/ansible-kind.git
    version: master
```

**Comment by thedatabaseme** [comment]
@pythoninthegrass I still don't get, why the meta/main.yml can't reside under the roles/ansible-kind/meta/ directory.

**Comment by pythoninthegrass** [comment]
Don't have the bandwidth to work on this. Appreciate the blueprint for getting a working Kind cluster via Ansible.

**Pull request closed without merging**
